// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'permission_model_v2.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_PermissionModelV2 _$PermissionModelV2FromJson(Map<String, dynamic> json) =>
    _PermissionModelV2(
      moduleAccessId: json['moduleAccessId'] as String?,
      companyId: json['companyId'] as String?,
      employeeId: json['employeeId'] as String?,
      leadAccess: json['leadAccess'] as bool?,
      template: json['template'] as bool?,
      email: json['email'] as bool?,
      customerViewAll: json['customerViewAll'] as bool?,
      customerOwnView: json['customerOwnView'] as bool?,
      customerCreate: json['customerCreate'] as bool?,
      customerDelete: json['customerDelete'] as bool?,
      customerEdit: json['customerEdit'] as bool?,
      projectViewAll: json['projectViewAll'] as bool?,
      projectOwnView: json['projectOwnView'] as bool?,
      projectCreate: json['projectCreate'] as bool?,
      projectDelete: json['projectDelete'] as bool?,
      projectEdit: json['projectEdit'] as bool?,
      timeSheetAccess: json['timeSheetAccess'] as bool?,
      timeSheetViewAll: json['timeSheetViewAll'] as bool?,
      timeSheetCreate: json['timeSheetCreate'] as bool?,
      timeSheetDelete: json['timeSheetDelete'] as bool?,
      timeSheetEdit: json['timeSheetEdit'] as bool?,
      leadModuleAccess: json['leadModuleAccess'] as bool?,
      leadViewAll: json['leadViewAll'] as bool?,
      leadCreate: json['leadCreate'] as bool?,
      leadDelete: json['leadDelete'] as bool?,
      leadEdit: json['leadEdit'] as bool?,
      workOrderAccess: json['workOrderAccess'] as bool?,
      workOrderViewAll: json['workOrderViewAll'] as bool?,
      workOrderCreate: json['workOrderCreate'] as bool?,
      workOrderDelete: json['workOrderDelete'] as bool?,
      workOrderEdit: json['workOrderEdit'] as bool?,
      kickOffAccess: json['kickOffAccess'] as bool?,
      kickOffViewAll: json['kickOffViewAll'] as bool?,
      kickOffCreate: json['kickOffCreate'] as bool?,
      kickOffDelete: json['kickOffDelete'] as bool?,
      kickOffEdit: json['kickOffEdit'] as bool?,
      kickoffDesinger: json['kickoffDesinger'] as bool?,
      quotationAccess: json['quotationAccess'] as bool?,
      quotationViewAll: json['quotationViewAll'] as bool?,
      quotationCreate: json['quotationCreate'] as bool?,
      quotationDelete: json['quotationDelete'] as bool?,
      quotationEdit: json['quotationEdit'] as bool?,
      bomAccess: json['bomAccess'] as bool?,
      bomViewAll: json['bomViewAll'] as bool?,
      bomEdit: json['bomEdit'] as bool?,
      bomCreate: json['bomCreate'] as bool?,
      bomDelete: json['bomDelete'] as bool?,
      momAccess: json['momAccess'] as bool?,
      momViewAll: json['momViewAll'] as bool?,
      momEdit: json['momEdit'] as bool?,
      momDelete: json['momDelete'] as bool?,
      momCreate: json['momCreate'] as bool?,
      checkSheetAccess: json['checkSheetAccess'] as bool?,
      checkSheetViewAll: json['checkSheetViewAll'] as bool?,
      checkSheetEdit: json['checkSheetEdit'] as bool?,
      checkSheetCreate: json['checkSheetCreate'] as bool?,
      checkSheetDelete: json['checkSheetDelete'] as bool?,
      checkSheetCheckByTl: json['checkSheetCheckByTL'] as bool?,
      salesOrderAccess: json['salesOrderAccess'] as bool?,
      salesOrderViewAll: json['salesOrderViewAll'] as bool?,
      salesOrderEdit: json['salesOrderEdit'] as bool?,
      salesOrderCreate: json['salesOrderCreate'] as bool?,
      salesOrderDelete: json['salesOrderDelete'] as bool?,
      patternSheetAccess: json['patternSheetAccess'] as bool?,
      patternSheetViewAll: json['patternSheetViewAll'] as bool?,
      patternSheetEdit: json['patternSheetEdit'] as bool?,
      patternSheetCreate: json['patternSheetCreate'] as bool?,
      patternSheetDelete: json['patternSheetDelete'] as bool?,
      performaInvoiceAccess: json['performaInvoiceAccess'] as bool?,
      performaInvoiceViewAll: json['performaInvoiceViewAll'] as bool?,
      performaInvoiceEdit: json['performaInvoiceEdit'] as bool?,
      performaInvoiceCreate: json['performaInvoiceCreate'] as bool?,
      performaInvoiceDelete: json['performaInvoiceDelete'] as bool?,
      taxInvoiceAccess: json['taxInvoiceAccess'] as bool?,
      taxInvoiceViewAll: json['taxInvoiceViewAll'] as bool?,
      taxInvoiceEdit: json['taxInvoiceEdit'] as bool?,
      taxInvoiceCreate: json['taxInvoiceCreate'] as bool?,
      taxInvoiceDelete: json['taxInvoiceDelete'] as bool?,
      timeSheetAttendanceApproveAccess:
          json['timeSheetAttendanceApproveAccess'] as bool?,
    );

Map<String, dynamic> _$PermissionModelV2ToJson(
  _PermissionModelV2 instance,
) => <String, dynamic>{
  'moduleAccessId': instance.moduleAccessId,
  'companyId': instance.companyId,
  'employeeId': instance.employeeId,
  'leadAccess': instance.leadAccess,
  'template': instance.template,
  'email': instance.email,
  'customerViewAll': instance.customerViewAll,
  'customerOwnView': instance.customerOwnView,
  'customerCreate': instance.customerCreate,
  'customerDelete': instance.customerDelete,
  'customerEdit': instance.customerEdit,
  'projectViewAll': instance.projectViewAll,
  'projectOwnView': instance.projectOwnView,
  'projectCreate': instance.projectCreate,
  'projectDelete': instance.projectDelete,
  'projectEdit': instance.projectEdit,
  'timeSheetAccess': instance.timeSheetAccess,
  'timeSheetViewAll': instance.timeSheetViewAll,
  'timeSheetCreate': instance.timeSheetCreate,
  'timeSheetDelete': instance.timeSheetDelete,
  'timeSheetEdit': instance.timeSheetEdit,
  'leadModuleAccess': instance.leadModuleAccess,
  'leadViewAll': instance.leadViewAll,
  'leadCreate': instance.leadCreate,
  'leadDelete': instance.leadDelete,
  'leadEdit': instance.leadEdit,
  'workOrderAccess': instance.workOrderAccess,
  'workOrderViewAll': instance.workOrderViewAll,
  'workOrderCreate': instance.workOrderCreate,
  'workOrderDelete': instance.workOrderDelete,
  'workOrderEdit': instance.workOrderEdit,
  'kickOffAccess': instance.kickOffAccess,
  'kickOffViewAll': instance.kickOffViewAll,
  'kickOffCreate': instance.kickOffCreate,
  'kickOffDelete': instance.kickOffDelete,
  'kickOffEdit': instance.kickOffEdit,
  'kickoffDesinger': instance.kickoffDesinger,
  'quotationAccess': instance.quotationAccess,
  'quotationViewAll': instance.quotationViewAll,
  'quotationCreate': instance.quotationCreate,
  'quotationDelete': instance.quotationDelete,
  'quotationEdit': instance.quotationEdit,
  'bomAccess': instance.bomAccess,
  'bomViewAll': instance.bomViewAll,
  'bomEdit': instance.bomEdit,
  'bomCreate': instance.bomCreate,
  'bomDelete': instance.bomDelete,
  'momAccess': instance.momAccess,
  'momViewAll': instance.momViewAll,
  'momEdit': instance.momEdit,
  'momDelete': instance.momDelete,
  'momCreate': instance.momCreate,
  'checkSheetAccess': instance.checkSheetAccess,
  'checkSheetViewAll': instance.checkSheetViewAll,
  'checkSheetEdit': instance.checkSheetEdit,
  'checkSheetCreate': instance.checkSheetCreate,
  'checkSheetDelete': instance.checkSheetDelete,
  'checkSheetCheckByTL': instance.checkSheetCheckByTl,
  'salesOrderAccess': instance.salesOrderAccess,
  'salesOrderViewAll': instance.salesOrderViewAll,
  'salesOrderEdit': instance.salesOrderEdit,
  'salesOrderCreate': instance.salesOrderCreate,
  'salesOrderDelete': instance.salesOrderDelete,
  'patternSheetAccess': instance.patternSheetAccess,
  'patternSheetViewAll': instance.patternSheetViewAll,
  'patternSheetEdit': instance.patternSheetEdit,
  'patternSheetCreate': instance.patternSheetCreate,
  'patternSheetDelete': instance.patternSheetDelete,
  'performaInvoiceAccess': instance.performaInvoiceAccess,
  'performaInvoiceViewAll': instance.performaInvoiceViewAll,
  'performaInvoiceEdit': instance.performaInvoiceEdit,
  'performaInvoiceCreate': instance.performaInvoiceCreate,
  'performaInvoiceDelete': instance.performaInvoiceDelete,
  'taxInvoiceAccess': instance.taxInvoiceAccess,
  'taxInvoiceViewAll': instance.taxInvoiceViewAll,
  'taxInvoiceEdit': instance.taxInvoiceEdit,
  'taxInvoiceCreate': instance.taxInvoiceCreate,
  'taxInvoiceDelete': instance.taxInvoiceDelete,
  'timeSheetAttendanceApproveAccess': instance.timeSheetAttendanceApproveAccess,
};
